services:
  - type: web
    name: smart-attendance
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn run:app
    disk:
      name: data
      mountPath: /var/data
      sizeGB: 1
    envVars:
      - key: SECRET_KEY
        sync: false
      - key: DB_HOST
        sync: false
      - key: DB_USER
        sync: false
      - key: DB_PASSWORD
        sync: false
      - key: DB_NAME
        sync: false
      - key: TWILIO_ACCOUNT_SID
        sync: false
      - key: TWILIO_AUTH_TOKEN
        sync: false
      - key: TWILIO_FROM
        sync: false
      - key: FACES_DIR
        value: /var/data/faces
      - key: MODEL_PATH
        value: /var/data/trained_model.yml
